### ISSUE TITLE
How to run example?

### ISSUE THREAD

**Issue by zhouhao27** [barbatus/ionic2-meteor#3]
I git clone your source and cd into your example/parties folder and run **meteor run**. But got a lot of error messages:

> client/lib/pipes.ts (1, 20): Cannot find module 'angular2/core'.
> client/lib/pipes.ts (5, 31): Cannot find module 'angular2-meteor'.
> client/lib/pipes.ts (11, 21): Cannot find namespace 'Meteor'.
> client/lib/pipes.ts (36, 22): Cannot find name 'Party'.
> client/lib/pipes.ts (43, 18): Property 'autorun' does not exist on type 'RsvpPipe'.
> client/login/login.ts (3, 20): Cannot find module 'ionic/ionic'.
> client/login/login.ts (5, 62): Cannot find module 'angular2/common'.
> client/login/login.ts (7, 43): Cannot find module 'meteor-accounts'.
> client/login/login.ts (9, 31): Cannot find module 'angular2-meteor'.
> client/login/login.ts (18, 9): Cannot find namespace 'Meteor'.
> 
> server/load-parties.ts (37, 5): Cannot find name 'Accounts'.
> server/load-parties.ts (43, 5): Cannot find name 'Accounts'.
> server/parties.ts (31, 1): Cannot find name 'Meteor'.
> server/parties.ts (32, 5): Cannot find name 'Counts'.
> server/parties.ts (37, 1): Cannot find name 'Meteor'.
> server/users.ts (3, 1): Cannot find name 'Meteor'.
> server/users.ts (7, 19): Cannot find name 'Meteor'.
> server/users.ts (9, 12): Cannot find name 'Meteor'.
> server/main.ts (6, 1): Cannot find name 'Meteor'.

How should I run the example? Thanks

**Comment by barbatus** [comment]
Please, see README how to add typings.
