### ISSUE TITLE
_transComplete

### ISSUE THREAD

**Issue by slippyC** [barbatus/ionic2-meteor#4]
Looks as if it isn't storing initial view or getting flagged as _transComplete. I believe that is why we are getting the view error now.  Setting _transComplete on initial view is destroying that view.  I'm trying to trace it back some, but I haven't had a lot of time to see when this is getting fired off when choosing something from menu.

**Comment by slippyC** [comment]
Actually it does look like it is working, even though error is getting thrown.  It looks like some of the packages weren't updated right.

Sorry about that.  I guess this error that keeps getting thrown will be resolved later.

**Comment by barbatus** [comment]
I am actually having the same issue even after the update.
Did you have change to try out parties demo from the example folder? Does it work for you?
