### ISSUE TITLE
Missing some ion icons

### ISSUE THREAD

**Issue by slippyC** [barbatus/ionic2-meteor#7]
Is it just me or are some of the ion icons missing?

The ion based, not ios or md.

I notice on some of the tutorials they are using ion-edit and so forth.  Those icons don't seem to be available.

Thanks for the up, to beta btw.  

They are on 2.0.0-beta.17 now...  This doesn't seem to have anything to do with the icon issue though.

**Comment by barbatus** [comment]
Current version is 2.0.0-beta.2 now. 2.0.0-beta.17 is a version of Ionic2 CLI.
I checked NPM, it contains only IOS and MD specific icons.
For more general Ionic icons, try this package https://atmospherejs.com/meteoric/ionicons-sass

**Comment by slippyC** [comment]
Alrighty, thanks man.
