### ISSUE TITLE
Missing typings for Count and Party

### ISSUE THREAD

**Issue by mjwheatley** [barbatus/ionic2-meteor#9]
I had to copy the typings from [Meteor App for the Angular2-Meteor tutorial](https://github.com/Urigo/meteor-angular2.0-socially) that you referenced.

**Comment by barbatus** [comment]
It's not clear what does it means they are missing?
All information is provided in the tutorial.
Party typings are a custom type typings that you need to add manually anyways
As for the Count typings, they are available here https://github.com/correpw/meteor-publish-counts.d.ts/blob/master/Counts.d.ts.

**Comment by mjwheatley** [comment]
I thought your example was incomplete somehow because I was receiving warnings that these two classes could not be found.  I didn't know where to find them, so I checked the tutorial that you referenced.  If they need to be added manually, maybe you could reference that fact in your readme and explain where to find them and how they should be added to the project.

**Comment by barbatus** [comment]
Which example do you mean? Party.d.ts is a definition file that is being filled in following the Angular2 tutorial for the Socially app. So if you download one of the tutorial step's version of the Socially and try it, you shouldn't have any errors (related to Party or Count), everything should be there.

**Comment by mjwheatley** [comment]
I was referring to your [example](https://github.com/barbatus/ionic2-meteor/tree/master/examples/parties) provided in this ionic2-meteor repository.

You reference "typings/party.d.ts" in the tsconfig.json
and "typings/Counts.d.ts" would also be needed.  The typings folder is generated until  you run the app for the first time.  Then those two definitions would need to be added manually.  I'm just trying to help direct people where to find them in case they are scratching their head like I was when trying to resolve the warning messages.

**Comment by barbatus** [comment]
Ah, I forgot about it already. Ok, I'll add them into the parties/typings, though you could PR it instead if you want.

**Comment by mjwheatley** [comment]
Sure.  I'll send you a PR.
